version: '3.9'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  vault:
    image: vault:latest
    container_name: vault
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    depends_on:
      - mysql
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "default-root-token"

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service
    ports:
      - 8080:8080
    links:
      - vault
      - mysql